### ISSUE TITLE
Street Fighter graphics issues

### ISSUE THREAD

**Issue by M-Walrus** [jotego/jt_gng#66]
Current April 2021 build has the following issues (youtube links are timestamped to issue occurence)

None of this is confirmed to real hardware.

1. Guys on right side holding planks in the bonus stages- the bottom one has a line from the background going through him, and there's a line missing from arms on top:
https://youtu.be/5TVZO4VB1yY?t=825

//**FIXED IN 2021/05/19 BUILD**// 2. When plane flies south on the map between stages, it splits in two: https://youtu.be/5TVZO4VB1yY?t=838

3. Brown line appears on right side of screen when continually fighting Sagat. Timestamped right before it shows up. Persists through continue screens into the next round and reappears randomly:
https://youtu.be/5TVZO4VB1yY?t=1045

**Comment by jotego** [comment]
I have fixed the plane bug in b9fd12. I will upload the file later today. There's a good chance that the bonus stage is the same problem. Could you please check it?

**Comment by M-Walrus** [comment]
I checked and the bonus stages still have the same issue. Plane is most definitely fixed though, nice work! 
Updating original post to reflect this.

**Comment by jotego** [comment]
It is due to a misalignment of the object and scroll layers. This got fixed when adjusting the LHBL signal going into the object circuitry for issue #70. Fixed in 518600b
